---
apiVersion: v1
kind: Secret
metadata:
  name: fishes-db-credentials
type: Opaque
data:
  user: YWRtaW4K
  password: cGxlYXNlY2hhbmdlbWU=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fishes-config
data:
  config.properties: |
    listen.port: :7007
    mode: RANDOM_NUMBER
---
kind: Deployment
apiVersion: apps/v1
metadata:  
  name: fishes-app
  labels:
    app: fishes-app
    group: micro-pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fishes-app
      group: micro-pet
  template:
    metadata:
      labels:
        app: fishes-app
        group: micro-pet
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: fishes-config
            items:
            - key: config.properties
              path: config.properties
      containers:
        - name: fishes
          image: localregistry:5000/micropet/fishes:dev
          imagePullPolicy: Always
          ports:
            - name: fishes
              containerPort: 7007
          volumeMounts:
            - name: config-volume
              mountPath: /config/
          livenessProbe:
            httpGet:
              port: 7007
              path: /liveness
            initialDelaySeconds: 10
            periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 7007
              path: /readiness
            initialDelaySeconds: 10
            periodSeconds: 2
          env:
            - name: SERVICE_CONFIG_DIR
              value: /config
            - name: DATABASE_URL
              value: jdbc:postgresql://fishes-db:5432/fishes
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: fishes-db-credentials
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fishes-db-credentials
                  key: password

      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fishes-service
  labels:
    app: fishes-app
    group: micro-pet
spec:
  ports:
    - protocol: TCP
      name: http-fishes
      port: 7007
  selector:
    app: fishes-app
    group: micro-pet
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: fishes-ingress
spec:
  rules:
    - host: k8s.mytanzu.xyz
      http:
        paths:
          - path: /fishes
            backend:
              serviceName: fishes-service
              servicePort: 7007


